name: Generate Macaroon Graph

on:
  # 每天国际时间 0 点运行一次
  schedule:
    - cron: "0 0 * * *" 
  # 允许手动点按钮触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Static Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # 生成静态SVG图，指定马卡龙蓝配色方案
            dist/macaroon-graph.svg?color_snake=invisible&color_dots=#ebedf0,#b0e0e6,#87cefa,#00bfff,#1e90ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
